/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Root */
        get: operations["get_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_profile_get"];
        put?: never;
        /** Create Profile */
        post: operations["create_profile_api_v1_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_v1_profile_patch"];
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Job */
        patch: operations["patch_job_api_v1_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Job Status */
        patch: operations["patch_job_status_api_v1_jobs__job_id__status_patch"];
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score Job */
        post: operations["score_job_api_v1_jobs__job_id__score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cover-letter/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Cover Letter */
        post: operations["regenerate_cover_letter_api_v1_jobs__job_id__cover_letter_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cover-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cover Letters */
        get: operations["list_cover_letters_api_v1_cover_letters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Task */
        post: operations["retry_task_api_v1_tasks__task_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "wishlist" | "applied" | "waiting" | "recruiter screen" | "interview scheduled" | "interviewing" | "final round" | "offer" | "accepted" | "rejected" | "withdrawn";
        /** AuthMeResponse */
        AuthMeResponse: {
            /** User Id */
            user_id: string;
            /** Session Id */
            session_id: string | null;
            /** Email */
            email: string | null;
        };
        /** BackgroundTaskResponse */
        BackgroundTaskResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string | null;
            /** Job Id */
            job_id: string | null;
            task_type: components["schemas"]["BackgroundTaskType"];
            status: components["schemas"]["BackgroundTaskStatus"];
            /** Provider Job Id */
            provider_job_id: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            } | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error Message */
            error_message: string | null;
            /** Attempt Count */
            attempt_count: number;
            /** Max Attempts */
            max_attempts: number;
            /** Can Retry */
            can_retry: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Last Attempt At */
            last_attempt_at: string | null;
            /** Next Retry At */
            next_retry_at: string | null;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * BackgroundTaskStatus
         * @enum {string}
         */
        BackgroundTaskStatus: "queued" | "running" | "completed" | "failed";
        /** BackgroundTaskSummaryResponse */
        BackgroundTaskSummaryResponse: {
            /** Id */
            id: string;
            task_type: components["schemas"]["BackgroundTaskType"];
            status: components["schemas"]["BackgroundTaskStatus"];
            /** Error Message */
            error_message: string | null;
            /** Result Score */
            result_score?: number | null;
            /** Result Verdict */
            result_verdict?: string | null;
            /** Attempt Count */
            attempt_count: number;
            /** Max Attempts */
            max_attempts: number;
            /** Can Retry */
            can_retry: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Last Attempt At */
            last_attempt_at: string | null;
            /** Next Retry At */
            next_retry_at: string | null;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * BackgroundTaskType
         * @enum {string}
         */
        BackgroundTaskType: "score_job" | "generate_cover_letter";
        /** CoverLetterListItemResponse */
        CoverLetterListItemResponse: {
            /** Id */
            id: string;
            /** Job Id */
            job_id: string;
            /** Evaluation Id */
            evaluation_id: string | null;
            /** Company */
            company: string | null;
            /** Role Title */
            role_title: string | null;
            current_status: components["schemas"]["ApplicationStatus"];
            /** Score */
            score?: number | null;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CoverLetterSummaryResponse */
        CoverLetterSummaryResponse: {
            /** Id */
            id: string;
            /** Evaluation Id */
            evaluation_id: string | null;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EvaluationSummaryResponse */
        EvaluationSummaryResponse: {
            /** Id */
            id: string;
            /** Score */
            score: number;
            /** Verdict */
            verdict: string;
            /** Top Strengths */
            top_strengths: string[];
            /** Critical Gaps */
            critical_gaps: string[];
            /** Feedback */
            feedback: string;
            /** Model */
            model: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Environment */
            environment: string;
            /** Services */
            services: {
                [key: string]: components["schemas"]["ServiceHealth"];
            };
        };
        /** JobCreateRequest */
        JobCreateRequest: {
            /** Description */
            description: string;
            /** Source Url */
            source_url?: string | null;
            /** Company */
            company?: string | null;
            /** Role Title */
            role_title?: string | null;
            /** Location */
            location?: string | null;
            /** @default waiting */
            current_status: components["schemas"]["ApplicationStatus"];
        };
        /** JobDetailResponse */
        JobDetailResponse: {
            /** Id */
            id: string;
            /** Profile Id */
            profile_id: string | null;
            /** Company */
            company: string | null;
            /** Role Title */
            role_title: string | null;
            /** Location */
            location: string | null;
            /** Source Url */
            source_url: string | null;
            /** Description */
            description: string;
            current_status: components["schemas"]["ApplicationStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Status History */
            status_history: components["schemas"]["StatusEventResponse"][];
            latest_evaluation?: components["schemas"]["EvaluationSummaryResponse"] | null;
            latest_cover_letter?: components["schemas"]["CoverLetterSummaryResponse"] | null;
            latest_task?: components["schemas"]["BackgroundTaskSummaryResponse"] | null;
        };
        /** JobListItemResponse */
        JobListItemResponse: {
            /** Id */
            id: string;
            /** Profile Id */
            profile_id: string | null;
            /** Company */
            company: string | null;
            /** Role Title */
            role_title: string | null;
            /** Location */
            location: string | null;
            /** Source Url */
            source_url: string | null;
            current_status: components["schemas"]["ApplicationStatus"];
            latest_evaluation?: components["schemas"]["EvaluationSummaryResponse"] | null;
            latest_cover_letter?: components["schemas"]["CoverLetterSummaryResponse"] | null;
            latest_task?: components["schemas"]["BackgroundTaskSummaryResponse"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** JobStatusUpdateRequest */
        JobStatusUpdateRequest: {
            status: components["schemas"]["ApplicationStatus"];
        };
        /** JobUpdateRequest */
        JobUpdateRequest: {
            /** Description */
            description?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Company */
            company?: string | null;
            /** Role Title */
            role_title?: string | null;
            /** Location */
            location?: string | null;
        };
        /** ProfileCreateRequest */
        ProfileCreateRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Location */
            location?: string | null;
            /** Resume Text */
            resume_text?: string | null;
            /** Context Text */
            context_text?: string | null;
            resume_upload?: components["schemas"]["UploadedProfileDocumentRequest"] | null;
            context_upload?: components["schemas"]["UploadedProfileDocumentRequest"] | null;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string | null;
            /** Location */
            location: string | null;
            /** Resume Text */
            resume_text: string;
            /** Context Text */
            context_text: string;
            /** Resume Version Id */
            resume_version_id: string;
            /** Resume Version Number */
            resume_version_number: number;
            /** Context Version Id */
            context_version_id: string;
            /** Context Version Number */
            context_version_number: number;
            resume_source_file?: components["schemas"]["StoredProfileDocumentResponse"] | null;
            context_source_file?: components["schemas"]["StoredProfileDocumentResponse"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProfileUpdateRequest */
        ProfileUpdateRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Location */
            location?: string | null;
            /** Resume Text */
            resume_text?: string | null;
            /** Context Text */
            context_text?: string | null;
            resume_upload?: components["schemas"]["UploadedProfileDocumentRequest"] | null;
            context_upload?: components["schemas"]["UploadedProfileDocumentRequest"] | null;
        };
        /** ServiceHealth */
        ServiceHealth: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "not_configured";
            /** Detail */
            detail: string;
        };
        /** StatusEventResponse */
        StatusEventResponse: {
            /** Id */
            id: string;
            previous_status: components["schemas"]["ApplicationStatus"] | null;
            next_status: components["schemas"]["ApplicationStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StoredProfileDocumentResponse */
        StoredProfileDocumentResponse: {
            /** File Name */
            file_name: string;
            /** Content Type */
            content_type: string | null;
            /** Size Bytes */
            size_bytes: number;
        };
        /** TaskAcceptedResponse */
        TaskAcceptedResponse: {
            /** Task Id */
            task_id: string;
            status: components["schemas"]["BackgroundTaskStatus"];
        };
        /** UploadedProfileDocumentRequest */
        UploadedProfileDocumentRequest: {
            /** File Name */
            file_name: string;
            /** Content Type */
            content_type?: string | null;
            /** Content Base64 */
            content_base64: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
        };
    };
    get_profile_api_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    create_profile_api_v1_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_v1_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListItemResponse"][];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_job_api_v1_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_job_status_api_v1_jobs__job_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_job_api_v1_jobs__job_id__score_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_cover_letter_api_v1_jobs__job_id__cover_letter_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cover_letters_api_v1_cover_letters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverLetterListItemResponse"][];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackgroundTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_task_api_v1_tasks__task_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
