"""Compatibility exports for shared OpenAI services."""

from jobfit_core.openai_service import (
    DEFAULT_OPENAI_MODEL,
    MAX_COVER_LETTER_BODY_WORDS,
    ModelRefusalError,
    OPENAI_MODEL_FALLBACK,
    OpenAIEvaluator,
    OpenAIValidationError,
    extract_output_text,
    extract_refusal_text,
    extract_response_items,
    is_model_access_error,
    normalize_content,
    normalize_cover_letter,
    sanitize_job_evaluation_payload,
    trim_cover_letter_body_paragraphs,
    trim_paragraph_to_word_limit,
    trim_text_to_word_limit,
    trim_to_sentence_limit,
    word_count,
)

__all__ = [
    "DEFAULT_OPENAI_MODEL",
    "MAX_COVER_LETTER_BODY_WORDS",
    "ModelRefusalError",
    "OPENAI_MODEL_FALLBACK",
    "OpenAIEvaluator",
    "OpenAIValidationError",
    "extract_output_text",
    "extract_refusal_text",
    "extract_response_items",
    "is_model_access_error",
    "normalize_content",
    "normalize_cover_letter",
    "sanitize_job_evaluation_payload",
    "trim_cover_letter_body_paragraphs",
    "trim_paragraph_to_word_limit",
    "trim_text_to_word_limit",
    "trim_to_sentence_limit",
    "word_count",
]
